service: consultant-profile

provider:
  name: aws
  profile: default
  region: eu-west-1
  runtime: nodejs8.0
  stage: dev
  environment:
    CONSULTANT_TABLE: ${self:service}-${opt:stage, self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.CONSULTANT_TABLE}"

custom:
  s3bucketname: Haedlight-CustomerProfile

functions:
  saveItem:
    handler: handler.saveItem
    events:
      - http:
          path: item
          method: post
  getItem:
    handler: handler.getItem
    events:
      - http:
          path: item/{itemId}
          method: get
  deleteItem:
    handler: handler.deleteItem
    events:
      - http:
          path: item/{itemId}
          method: delete
  updateItem:
    handler: handler.updateItem
    events:
      - http:
          path: item/{itemId}
          method: put

resources:
  Resources:
    ConsultantDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      #DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: "itemId"
            AttributeType: "S" 

        KeySchema:
          -
            AttributeName: "itemId"
            KeyType: "HASH"

        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.CONSULTANT_TABLE}


  #  ApiGatewayRestApi:
  #   Type: AWS::ApiGateway::RestApi
  #    Properties:
  #      Name: Consultant Profile

  #  DomainName:
  #    Type: AWS::ApiGateway::DomainName
  #    Properties:
  #      CertificateArn: 
  #      DomainName: 

  #  BasePathMapping:
  #    Type: AWS::ApiGateway::BasePathMapping
  #    Properties:
        # BasePath: Must be missing for empty path
  #      DomainName:
  #        Ref: DomainName
  #      RestApiId:
  #        Ref: ApiGatewayRestApi
  #      Stage: 

    #
    # Route 53
    #

  #  Route53Record:
  #    Type: AWS::Route53::RecordSet
  #    Properties:
  #      AliasTarget:
  #        DNSName:
  #          "Fn::GetAtt": DomainName.DistributionDomainName
  #        HostedZoneId:
  #          "Fn::GetAtt": DomainName.DistributionHostedZoneId
  #      Comment: Record set for Consultant Profile
  #      HostedZoneName: 
  #      Name:
  #        Ref: DomainName
  #      Type: A
